name: Discourage New Snapshots On CI

description: >
  Warn if any files in the provided regex (defaults to test snapshot files) pattern are strictly added (not moved or renamed) in a PR.

inputs:
  regex:
    description: 'Regex pattern to check for added files.'
    required: false
    default: '.*__snapshots__.*|.*\.snap$'

outputs:
  result:
    description: 'pass or fail based on the check.'
    value: ''

runs:
  using: "composite"
  steps:
    - name: "Fetch the pull request merge branch"
      run: |
        git fetch origin pull/${{ github.event.pull_request.number }}/merge:pr-merge
        git checkout pr-merge
      shell: bash

    - name: "Fetch the base branch"
      run: |
        git fetch --unshallow origin ${{ github.event.pull_request.base.ref }}
      shell: bash

    - name: "Generate the diff of changed files"
      run: |
        merge_base=$(git merge-base origin/${{ github.event.pull_request.base.ref }} pr-merge)
        git diff --diff-filter=A -M -C --find-copies-harder --name-status $merge_base...pr-merge > diff_output.txt
        cat diff_output.txt
        echo "diff_file=diff_output.txt" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check Added Snapshot Files with Grep
      id: check_added_files
      run: |
        # Use grep to find files that match the regex pattern in the added files
        if grep -Eq "${{ inputs.regex }}" diff_output.txt; then
          echo "Found files matching the pattern."
          echo "::warning::Found files matching the pattern"
          echo "result=fail" >> $GITHUB_ENV
        else
          echo "No files matching the pattern found."
          echo "result=pass" >> $GITHUB_ENV
        fi
      shell: bash