name: Dont Allow New Snapshots On CI

description: >
  Warn if any files in the provided regex pattern are strictly added (not moved or renamed) in a PR.

inputs:
  regex:
    description: 'Regex pattern to check for added files.'
    required: false
    default: '.*__snapshots__.*|.*\.snap$'

outputs:
  result:
    description: 'pass or fail based on the check.'
    value: ''

runs:
  using: "composite"
  steps:
    - name: "Fetch the pull request merge branch"
      run: |
        git fetch origin pull/${{ github.event.pull_request.number }}/merge:pr-merge
        git checkout pr-merge
      shell: bash

    - name: "Fetch the base branch"
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}
      shell: bash

    - name: "Generate the diff of changed files and Filter by Flags and Regex"
      run: | # -M:Detect renames -C:Detect copies --find-copies-harder:Find copies within the same commit
        git diff --diff-filter=A -M -C --find-copies-harder --name-status origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -E "${{ inputs.regex }}" > diff_output.txt
        cat diff_output.txt
        echo "diff_file=diff_output.txt" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set Result
      run: |
        # Check if diff_output.txt contains any lines
        if [ -s diff_output.txt ]; then
          echo "::warning file=diff_output.txt::Matching files found. See the list in diff_output.txt"
        else
          echo "No matching files found. Passing step."
        fi
      shell: bash