name: Discourage New Snapshots On CI

description: >
  Warn if any files in the provided regex (defaults to test snapshot files) pattern are strictly added (not moved or renamed) in a PR.

inputs:
  regex:
    description: 'Regex pattern to check for added files.'
    required: false
    default: '.*__snapshots__.*|.*\.snap$'

outputs:
  result:
    description: 'pass or fail based on the check.'
    value: ''

runs:
  using: "composite"
  steps:
    - name: "Fetch the pull request merge branch"
      run: |
        git fetch origin pull/${{ github.event.pull_request.number }}/merge:pr-merge
        git checkout pr-merge
      shell: bash

    - name: "Fetch the base branch"
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}
      shell: bash

    - name: "Find the common ancestor commit"
      run: |
        common_ancestor=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
        echo $common_ancestor
        echo "common_ancestor=$common_ancestor" >> $GITHUB_OUTPUT
      shell: bash

    - name: "List strictly added files"
      run: |
        added_files=$(git log --diff-filter=A --name-only --pretty="" ${{ steps.find_common_ancestor.outputs.common_ancestor }}..HEAD)
        echo "$added_files" > added_files.txt
        cat added_files.txt
        echo "added_files=added_files.txt" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check Added Snapshot Files with Grep
      id: check_added_files
      run: |
        # Use grep to find files that match the regex pattern in the added files
        if grep -Eq "${{ inputs.regex }}" added_files.txt; then
          echo "Found files matching the pattern."
          echo "result=fail" >> $GITHUB_ENV
        else
          echo "No files matching the pattern found."
          echo "result=pass" >> $GITHUB_ENV
        fi
      shell: bash